### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bryphe** [thangngoc89/sketch-v2#2]
Just saw that there was no License specified - is that intentional? Or were you planning on adding a License? Looks like Sketch v1 used the Apache 2.0 License

**Comment by thangngoc89** [comment]
@bryphe Does Apache 2.0 sound good to you?

**Comment by bryphe** [comment]
@thangngoc89 - Apache 2.0 is great! 👍

**Comment by thangngoc89** [comment]
Added Apache 2.0 in 4b5e625
